GET http://localhost:8081/api/v1/users?page=0&size=10&sort=name,asc

### Autenticação
POST http://localhost:8081/api/v1/auth/login
Content-Type: application/json

{
  "name": "Jerameel Gonga",
  "email": "jerameel.gonga@mail.com"
}

### Criar Usuário
POST http://localhost:8081/api/v1/users
Content-Type: application/json

{
  "name": "Novo Usuário",
  "email": "novo.usuario@example.com",
  "password": "senha123"
}

### Listar Usuários
GET http://localhost:8081/api/v1/users

### Buscar Usuário por ID
GET http://localhost:8081/api/v1/users/1

### Atualizar Usuário
PUT http://localhost:8081/api/v1/users/1
Content-Type: application/json

{
  "name": "Usuário Atualizado",
  "email": "usuario.atualizado@example.com"
}

### Deletar Usuário
DELETE http://localhost:8081/api/v1/users/1